# [ MIBLO ]
language: rust

# [ HANDLEBARS ]
template_dir: "handlebars"

# [ ROUTES ]
routes:
    - method: get
      path: "/users"
      model: "Users"

    #- method: post
    #  path: "/users/create"
    #  model: "Users"

    - method: delete
      path: "/users/delete/{user_id}"
      model: "Users"

    - method: patch
      path: "/users/patch/{user_id}"
      model: "Users"

# [ DATABASES ]
database:
    - db_connexion: mysql
      db_host: 100.120.71.76
      db_port: 3306
      db_database: miblo_test
      db_username: askeet
      db_password: Romain2024!
# [ SERVER ]
server:
    - port: 4000
      address: "0.0.0.0"
# [ CONFIGURATIONS ]
auth: true

# [ MODEL ]
models:
    - name: "Users"
      method: [get,patch,delete]
      fields:
          - name: id
            type: Int
            primary_key: true
            auto_increment: true
          - name: email
            type: String
            not_null: true
            unique: true
          - name: password
            type: String
            not_null: true
          - name: first_name
            type: String
            not_null: true
          - name: last_name
            type: String
            not_null: true
          - name: phone
            type: String
            not_null: true
          - name: pseudo
            type: String
            not_null: true
