# [ HANDLEBARS ]
template_dir: "handlebars"

# [ ROUTES ]
route:
  - method: get
    path: "/users"
    model: "Users"

  - method: post
    path: "/users/create"
    model: "Users"

  - method: get
    path: "/survey"
    model: "Survey"
  
  - method: post
    path: "/survey/create"
    model: "Survey"


# [ DATABASES ]
database:
  - DB_CONNECTION: mysql
    DB_HOST: 100.120.71.76
    DB_PORT: 3306
    DB_DATABASE: miblo_test
    DB_USERNAME: askeet
    DB_PASSWORD: Romain2024!
# [ SERVER ]
server:
  - port: 4000
  - adress: 0.0.0.0
# [ CONFIGURATIONS ]
auth: true

# [ MODEL ]
models:
  - name: "Users"
    fields:
      - name: id
        type: Int
        primary_key: true
        auto_increment: true
      - name: email
        type: String
        not_null: true
        unique: true
      - name: password
        type: String
        not_null: true
      - name: first_name
        type: String
        not_null: true
      - name: last_name
        type: String
        not_null: true
      - name: phone
        type: String
        not_null: true
      - name: pseudo
        type: String
        not_null: true
  
  - name: "Survey"
    fields:
      - name: name
        type: string
      - name: last_name
        type: string
  
  - name: "CACA"
    fields:
      - name: first_name
        type: string
      - name: last_name
        type: string

